from __future__ import annotations

from typing import Any, Dict

from office_app.server.image_generation_service import decode_generated_image

from .dependencies import HandlerDeps


def build_image_handlers(deps: HandlerDeps) -> Dict[str, Any]:
    def handle_image_generate(args: Dict[str, Any]) -> Dict[str, Any]:
        workspace_id = deps.resolve_workspace_id("office.image_generate", args)
        prompt = str(args.get("prompt") or args.get("description") or "").strip()
        if not prompt:
            raise deps.error_missing_required_field("prompt")
        model = str(args.get("model") or "").strip() or None
        session_id = str(args.get("session_id") or "").strip() or None
        state = deps.kernel.get_state(workspace_id)
        source_room = str(args.get("source_room") or state.get("active_room") or "art_department")
        source_persona = str(args.get("source_persona") or state.get("active_persona") or "Creative Director")

        generated = deps.image_generation_service.generate_image(prompt=prompt, model=model)
        record = deps.workspace_file_service.upload_file(
            workspace_id=workspace_id,
            original_name=str(generated["filename"]),
            content_base64=str(generated["content_base64"]),
            mime_type=str(generated["mime_type"]),
            kind="generated_image",
            scope="room",
            scope_ref="art_department",
            description=f"Generated by {source_persona} in {source_room}. Prompt: {prompt}",
            uploaded_by_session_id=session_id,
        )
        structured = {
            "workspace_id": workspace_id,
            "provider": "gemini",
            "model": generated["model"],
            "prompt": prompt,
            "file": record,
        }
        return {
            "structuredContent": structured,
            "content": [
                {
                    "type": "text",
                    "text": (
                        f"Art Department generated an image and saved it as {record['original_name']} "
                        f"({record['file_id']})."
                    ),
                }
            ],
        }

    return {"office.image_generate": handle_image_generate}
